approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

packageExtensions:
  "@11ty/eleventy-plugin-bundle@*":
    peerDependencies:
      posthtml: "*"
